source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MLVerticalProgressView_Example', :exclusive => true do
  pod "MLVerticalProgressView", :path => "../"
end

target 'MLVerticalProgressView_Tests', :exclusive => true do
  pod "MLVerticalProgressView", :path => "../"

  pod 'FBSnapshotTestCase'
end
